json.extract! eight_ms_analysis,
              :id,
              :complaint_id,
              :consequence,
              :manpower,
              :machines,
              :materials,
              :methods,
              :management,
              :created_at,
              :updated_at
